server:
  port: 10005
spring:
  application:
    name: order-service
eureka:
  client:
    registerWithEureka: true #\u670D\u52A1\u6CE8\u518C\u5F00\u5173
    fetchRegistry: true #\u670D\u52A1\u53D1\u73B0\u5F00\u5173
    serviceUrl: #Eureka\u5BA2\u6237\u7AEF\u4E0EEureka\u670D\u52A1\u7AEF\u8FDB\u884C\u4EA4\u4E92\u7684\u5730\u5740\uFF0C\u591A\u4E2A\u4E2D\u95F4\u7528\u9017\u53F7\u5206\u9694
      defaultZone: ${EUREKA_SERVER:http://localhost:10000/eureka/}
  instance:
    prefer-ip-address:  true  #\u5C06\u81EA\u5DF1\u7684ip\u5730\u5740\u6CE8\u518C\u5230Eureka\u670D\u52A1\u4E2D
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #\u6307\u5B9A\u5B9E\u4F8Bid
